# Generated by Django 4.2.3 on 2023-08-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_heroiconinfo_hero_artefacts_test_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefacts',
            name='test_add',
        ),
    ]
