# Generated by Django 4.2.3 on 2023-08-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_artefacts_test_add'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artefacts',
            options={'verbose_name': 'Артефакт', 'verbose_name_plural': 'Артефакти'},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажі'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'Зброя', 'verbose_name_plural': 'Зброя'},
        ),
        migrations.RemoveField(
            model_name='artefacts',
            name='art_info',
        ),
    ]
